import type { Metadata } from 'next';
import './globals.css';
import { TLang } from '@/locales/i18n.config';
import React, { PropsWithChildren } from 'react';
import { I18nProviderClient } from '@/locales/client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout(
  props: {
    params: Promise<{ lang: TLang }>;
  } & PropsWithChildren,
) {
  const params = React.use(props.params);

  const { lang } = params;

  const { children } = props;

  return (
    <html lang={lang.split('-')[0]} suppressHydrationWarning>
      <body className="bg-neutral-50 text-neutral-800 font-serif cursor-default">
        <I18nProviderClient locale={lang}>{children}</I18nProviderClient>
      </body>
    </html>
  );
}
